import { LoadingOverlay } from "@/components/common/LoadingOverlay";
import StampRecordScanner from "@/components/stamps/StampRecordScanner";
import { useStampRecordQRCode } from "@/lib/hooks/useStampRecordQRCode";
import { claimStampRecord } from "@/lib/services/stamps.service";
import { StampRecordQRCode } from "@/types/stamps";
import { BarcodeScanningResult } from "expo-camera";
import { useState } from "react";
import { Text, View } from "react-native";
import Toast from "react-native-toast-message";

export default function AddRewardScreen() {

  const [isLoading, setIsLoading] = useState<boolean>(false);
  const { decode } = useStampRecordQRCode();

  const handleScan = async (scanningResult: BarcodeScanningResult) => {
    const callClaimStampRecord = async (stampRecordId: string) => {
      return claimStampRecord(stampRecordId);
    }
    try {
      setIsLoading(true);
      const stampRecordQRCode: StampRecordQRCode = decode(scanningResult.data);
      const res = await callClaimStampRecord(stampRecordQRCode.stampRecordId);
      console.debug("stamp card claimed:", res.stampRecordId, res.state);
      Toast.show({
        type: "success",
        text1: "Stamp successfully claimed!"
      })

    } catch (error) {
      Toast.show({
        type: "error",
        text1: "Unable to claim record"
      })
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <View>
      <View className="flex justify-center items-center mb-2">
        <Text className="text-3xl font-bold mb-2">Claim your reward</Text>
        <Text className="text-md italic text-gray-500">Scan the QR code generated by the merchant</Text>
      </View>
      <View className="items-center justify-center">
        {isLoading ? (
          <LoadingOverlay />
        ) : (
          <View className="h-96 w-96 border border-gray-300 rounded-lg overflow-hidden">
            <StampRecordScanner
              onScanned={handleScan}
            />
          </View>
        )}
      </View>
    </View >
  );
}